FROM python:3.9.14-slim

WORKDIR /app/

RUN pip --no-cache-dir install poetry==1.2.0 && poetry config virtualenvs.create false

WORKDIR /app/bluelib
COPY bluelib/pyproject.toml pyproject.toml
RUN poetry install --no-root

WORKDIR /app/preprocessing
COPY preprocessing/pyproject.toml pyproject.toml
RUN poetry install --no-root

WORKDIR /app/bluelib
COPY bluelib .
RUN poetry install

WORKDIR /app/preprocessing
COPY preprocessing .
RUN poetry install

RUN pip --no-cache-dir install flake8==4.0.1 black==22.3 isort==5.10.1 mypy==0.950
