---
DISABLE: [SPELL]
IGNORE_GENERATED_FILES: true
DISABLE_LINTERS: [PYTHON_BANDIT, REPOSITORY_CHECKOV, REPOSITORY_TRIVY, REPOSITORY_GITLEAKS, REPOSITORY_SECRETLINT]
PYTHON_ISORT_CONFIG_FILE: LINTER_DEFAULT
PYTHON_BLACK_CONFIG_FILE: LINTER_DEFAULT
PYTHON_MYPY_CONFIG_FILE: pyproject.toml
PYTHON_PYLINT_ARGUMENTS: "--disable import-error,no-name-in-module"
PYTHON_BLACK_DISABLE_ERRORS: false
PYTHON_ISORT_DISABLE_ERRORS: false
YAML_FILTER_REGEX_EXCLUDE: '(.*/kustomization\.yaml)'
PRE_COMMANDS:
  - command: pip install --no-deps $CI_PROJECT_DIR/bluelib
    cwd: "root"
